version: "3.7"

networks:
  web:
    external: true
  internal:
    external: false

services:
  cocoa:
    build: .
    ports:
      - "5000:5000"
   
#   db:
#     image: "postgres:12.2-alpine"
#     #restart: always
#     container_name: db
#     ports:
#       - "5432:5432"
#     env_file: ./.env
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#       - POSTGRES_DB=${POSTGRES_DB}
#     labels:
#       - traefik.enable=false
#     volumes:
#       - ./db:/var/lib/postgresql

#     networks:
#       - internal

  