version: "3.7"

networks:
  web:
    external: true
  internal:
    external: false

services:
  cocoa:
    container_name: cocoa
    build: .
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}    
      - BOT_PREFIX=${BOT_PREFIX}
   
  db:
    container_name: postgres
    image: "postgres:12.2-alpine"
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}  
    networks:
      - internal

  